//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPCPWebApiServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class CitiesLKP
    {
        public int CityID { get; set; }
        public string CityName { get; set; }
        public Nullable<int> CountyID { get; set; }
        public int StateID { get; set; }
        public Nullable<int> TimeZoneID { get; set; }
        public int IsTownship { get; set; }
        public int ParentTownshipID { get; set; }
    }
}
