//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPCPWebApiServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberPlanInstallmentMapping
    {
        public int MemberPlanInstallmentID { get; set; }
        public Nullable<int> MemberPlanID { get; set; }
        public Nullable<int> PaymentDetailsID { get; set; }
        public Nullable<System.DateTime> PaymentDueDate { get; set; }
        public Nullable<decimal> PaymentAmount { get; set; }
        public Nullable<decimal> InstallmentAmount { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<decimal> PaidAmount { get; set; }
        public string PaymentStatus { get; set; }
    
        public virtual MemberPlan MemberPlan { get; set; }
    }
}
