//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPCPWebApiServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberCredential
    {
        public int CredentialID { get; set; }
        public int MemberID { get; set; }
        public string UserName { get; set; }
        public string UserPassword { get; set; }
        public string UserStatus { get; set; }
        public Nullable<int> WrongLoginCount { get; set; }
        public Nullable<System.DateTime> PasswordExpiryDate { get; set; }
        public Nullable<System.DateTime> UserNameExpiryDate { get; set; }
        public Nullable<bool> IsTermsAccepted { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
