//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPCPWebApiServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModuleUseCas
    {
        public int UseCaseID { get; set; }
        public Nullable<int> ModuleID { get; set; }
        public string ModuleName { get; set; }
        public string UseCaseName { get; set; }
        public Nullable<bool> IsVisiable { get; set; }
    }
}
