//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPCPWebApiServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrganizationPlan
    {
        public int OrganizationPlanID { get; set; }
        public int PlanID { get; set; }
        public int OrganizationID { get; set; }
        public Nullable<System.DateTime> PlanstartDate { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual Plan Plan { get; set; }
        public virtual Organization Organization { get; set; }
    }
}
