//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPCPWebApiServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class PPCP_CODE_LKP
    {
        public int PPCP_CODE_ID { get; set; }
        public string PREFIX { get; set; }
        public int SNO { get; set; }
        public string SUFFIX { get; set; }
        public Nullable<int> SNO_PADDING { get; set; }
        public System.DateTime FROM_DATE { get; set; }
        public Nullable<System.DateTime> TO_DATE { get; set; }
        public string DESCRIPTION { get; set; }
        public int CODE_TYPE_ID { get; set; }
    }
}
