//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPCPWebApiServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeZonesLKP
    {
        public int TimeZoneID { get; set; }
        public string TimeZoneName { get; set; }
        public string TimeZoneOffset { get; set; }
        public bool IsDayLightSaving { get; set; }
    }
}
