//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPCPWebApiServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionstoPractice
    {
        public int ID { get; set; }
        public Nullable<int> MemberID { get; set; }
        public string MemberName { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string PlanName { get; set; }
        public string DoctorName { get; set; }
        public Nullable<decimal> AmountPaid { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<int> OrganizationID { get; set; }
        public Nullable<int> MemberPlanID { get; set; }
        public string OrganizationName { get; set; }
    }
}
